using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Autonomy.Domain;
using Autonomy.UnityIntegration;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;

public static class P46M01VoiceBootstrapAudit
{
    private const string Prefix = "[P46M-01][Audit]";
    private const string BootstrapPath = "Assets/Scripts/Autonomy/UnityIntegration/ExperimentVoicePipelineBootstrap.cs";
    private const string ControllerPath = "Assets/Scripts/Autonomy/UnityIntegration/VoiceRecognitionController.cs";
    private const string BackendPath = "Assets/Scripts/Autonomy/UnityIntegration/SherpaOnnxASRBackend.cs";
    private const string WorkerPath = "Assets/Scripts/Autonomy/UnityIntegration/SherpaOnnxAndroidDecodeWorker.cs";
    private const string ProtocolPath = "Assets/Scripts/ExperimentRuntimeProtocolUI.cs";
    private const string OrchestratorPath = "Assets/Scripts/ExperimentSessionOrchestrator.cs";

    [MenuItem("Tools/Experiment/P46M-01 Audit Voice Bootstrap")]
    public static void RunFromMenu()
    {
        bool passed = RunAudit(out string report);
        Debug.Log(report);
        EditorUtility.DisplayDialog("P46M-01 Voice Bootstrap", passed ? "PASS" : "FAIL", "Aceptar");
    }

    public static void RunForBatch()
    {
        bool passed = RunAudit(out string report);
        Debug.Log(report);
        if (!passed)
        {
            throw new InvalidOperationException("P46M-01 audit failed. See Editor log for details.");
        }
    }

    public static bool RunAudit(out string report)
    {
        List<string> lines = new();
        int passed = 0;
        int failed = 0;

        void Check(string id, bool condition, string detail)
        {
            if (condition)
            {
                passed++;
                lines.Add($"PASS {id}: {detail}");
            }
            else
            {
                failed++;
                lines.Add($"FAIL {id}: {detail}");
            }
        }

        string bootstrap = Read(BootstrapPath);
        string controller = Read(ControllerPath);
        string backend = Read(BackendPath);
        string worker = Read(WorkerPath);
        string protocol = Read(ProtocolPath);
        string orchestrator = Read(OrchestratorPath);
        string allVoiceRuntime = string.Join("\n", bootstrap, controller, backend, worker, protocol, orchestrator);

        Check("authority_single", Count(bootstrap, "RuntimeInitializeOnLoadMethod") == 1 && Count(allVoiceRuntime, "class ExperimentVoicePipelineBootstrap") == 1,
            "ExperimentVoicePipelineBootstrap is the single persistent bootstrap authority");
        Check("permission_declared_or_generated", HasGeneratedRecordAudioPermission() || allVoiceRuntime.Contains("Permission.Microphone", StringComparison.Ordinal),
            "RECORD_AUDIO is present in the generated manifest or generated by the explicit Unity microphone permission path");
        Check("permission_check", bootstrap.Contains("HasUserAuthorizedPermission", StringComparison.Ordinal) && bootstrap.Contains("microphone_permission_state_checked", StringComparison.Ordinal),
            "permission is checked and measured before use");
        Check("permission_callbacks", bootstrap.Contains("PermissionGranted", StringComparison.Ordinal) && bootstrap.Contains("PermissionDeniedAndDontAskAgain", StringComparison.Ordinal),
            "granted, denied and don't-ask-again callbacks are retained by the persistent authority");
        Check("no_reprompt_granted", bootstrap.Contains("if (granted)", StringComparison.Ordinal) && bootstrap.Contains("already_granted", StringComparison.Ordinal),
            "already-granted permission bypasses the request");
        Check("prewarm_model", bootstrap.Contains("asr_model_load_started", StringComparison.Ordinal) && bootstrap.Contains("asr_model_load_completed", StringComparison.Ordinal),
            "model prewarm has start/completion telemetry");
        Check("prewarm_recognizer", bootstrap.Contains("asr_recognizer_create_started", StringComparison.Ordinal) && worker.Contains("PrepareRecognizerAsync", StringComparison.Ordinal),
            "recognizer is created on the dedicated worker before an utterance");
        Check("shared_backend", controller.Contains("SharedBackend", StringComparison.Ordinal) && controller.Contains("sharedSherpaBackend", StringComparison.Ordinal) == false,
            "scene controllers consume the persistent shared backend");
        Check("no_fixed_10_15_wait", !allVoiceRuntime.Contains("WaitForSeconds(10", StringComparison.Ordinal) && !allVoiceRuntime.Contains("WaitForSeconds(15", StringComparison.Ordinal) && !allVoiceRuntime.Contains("Task.Delay(10000", StringComparison.Ordinal) && !allVoiceRuntime.Contains("Task.Delay(15000", StringComparison.Ordinal),
            "no fixed 10-15 second activation delay exists");
        Check("c11_ui_gate", protocol.Contains("voiceReady", StringComparison.Ordinal) && protocol.Contains("c11_trial_start_blocked_voice_pipeline_not_ready", StringComparison.Ordinal),
            "C11 begin button and callback both require authoritative readiness");
        Check("orchestrator_gate", orchestrator.Contains("pendingPlanEntry", StringComparison.Ordinal) && orchestrator.Contains("voice_pipeline_not_ready", StringComparison.Ordinal),
            "programmatic trial start cannot consume C11 while ASR is unavailable");
        Check("activation_before_trial", Index(orchestrator, "SetExperimentVoicePipelineActive(\n                        true") < Index(orchestrator, "_instrumentation?.StartTrial()"),
            "capture activation is ordered before experiment trial start");
        Check("c00_c10_deactivated", orchestrator.Contains("voice_disabled_by_condition", StringComparison.Ordinal) && controller.Contains("if (!_voicePipelineActivated)", StringComparison.Ordinal),
            "non-voice conditions leave capture and processing inactive");
        Check("trial_boundary_deactivation", orchestrator.Contains("DeactivateVoicePipelineAtTrialBoundary", StringComparison.Ordinal),
            "voice capture is disabled when each trial closes");
        Check("denied_recoverable", protocol.Contains("Reintentar reconocimiento vocal", StringComparison.Ordinal) && protocol.Contains("Volver al inicio", StringComparison.Ordinal),
            "permission/preparation failures are visible and recoverable");
        Check("telemetry_complete", RequiredTelemetryEvents().All(allVoiceRuntime.Contains),
            "all P46M-01 timing and first-command events are present");
        Check("timeout_bounded", bootstrap.Contains("PreparationTimeoutMs", StringComparison.Ordinal) && bootstrap.Contains("voice_pipeline_prepare_timeout", StringComparison.Ordinal),
            "preparation has an explicit failure timeout rather than an indefinite wait");
        Check("condition_matrix", ExperimentCompensatedConditionOrder.IsFinalWithinSubjectOrder(new[]
            {
                ExperimentCompensatedConditionOrder.C00,
                ExperimentCompensatedConditionOrder.C10,
                ExperimentCompensatedConditionOrder.C11
            }), "C00/C10/C11 are valid and C01 is absent from the final order");
        Check("missing_scripts", CountMissingScriptsInTargetScenes(out string missingDetail) == 0, missingDetail);
        Check("metas_present", File.Exists(Absolute(BootstrapPath + ".meta")) && File.Exists(Absolute("Assets/Scripts/Autonomy/BT/Tests/VoicePipelineBootstrapTests.cs.meta")),
            "new runtime and test scripts have versioned .meta files");

        lines.Insert(0, $"{Prefix} {(failed == 0 ? "PASS" : "FAIL")} {passed}/{passed + failed}");
        report = string.Join("\n", lines);
        string outputDirectory = Absolute("Logs/P46M01_VoicePermissionAndPrewarm");
        Directory.CreateDirectory(outputDirectory);
        File.WriteAllText(Path.Combine(outputDirectory, "P46M01_audit.txt"), report);
        return failed == 0;
    }

    private static IEnumerable<string> RequiredTelemetryEvents()
    {
        return new[]
        {
            "app_voice_bootstrap_started",
            "microphone_permission_state_checked",
            "microphone_permission_request_started",
            "microphone_permission_request_completed",
            "microphone_permission_granted",
            "microphone_permission_denied",
            "asr_model_load_started",
            "asr_model_load_completed",
            "asr_recognizer_create_started",
            "asr_recognizer_create_completed",
            "microphone_open_started",
            "microphone_open_completed",
            "voice_pipeline_prepared",
            "voice_pipeline_activated",
            "voice_pipeline_deactivated",
            "c11_condition_entered",
            "c11_trial_started",
            "first_voice_command_received",
            "first_voice_command_accepted",
            "first_voice_command_rejected",
            "voice_pipeline_prepare_failed"
        };
    }

    private static int CountMissingScriptsInTargetScenes(out string detail)
    {
        string[] scenePaths =
        {
            "Assets/Scenes/experiment_start_scene.unity",
            "Assets/Scenes/final_scene.unity",
            "Assets/Scenes/autonomous_demo_step22_multimodal_bridge.unity"
        };
        int total = 0;
        foreach (string scenePath in scenePaths)
        {
            Scene scene = EditorSceneManager.OpenScene(scenePath, OpenSceneMode.Single);
            foreach (GameObject root in scene.GetRootGameObjects())
            {
                foreach (Transform transform in root.GetComponentsInChildren<Transform>(true))
                {
                    total += GameObjectUtility.GetMonoBehavioursWithMissingScriptCount(transform.gameObject);
                }
            }
        }

        detail = $"target scenes missing scripts={total}";
        return total;
    }

    private static bool HasGeneratedRecordAudioPermission()
    {
        string library = Absolute("Library/Bee/Android");
        if (!Directory.Exists(library))
        {
            return false;
        }

        return Directory.GetFiles(library, "AndroidManifest.xml", SearchOption.AllDirectories)
            .Any(path => File.ReadAllText(path).Contains("android.permission.RECORD_AUDIO", StringComparison.Ordinal));
    }

    private static string Read(string projectRelativePath)
    {
        string path = Absolute(projectRelativePath);
        return File.Exists(path) ? File.ReadAllText(path) : string.Empty;
    }

    private static string Absolute(string projectRelativePath)
    {
        return Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), projectRelativePath));
    }

    private static int Count(string text, string value)
    {
        if (string.IsNullOrEmpty(text) || string.IsNullOrEmpty(value))
        {
            return 0;
        }

        int count = 0;
        int index = 0;
        while ((index = text.IndexOf(value, index, StringComparison.Ordinal)) >= 0)
        {
            count++;
            index += value.Length;
        }

        return count;
    }

    private static int Index(string text, string value)
    {
        int index = text.IndexOf(value, StringComparison.Ordinal);
        return index < 0 ? int.MaxValue : index;
    }
}
